version: "3.0"

services:
  app:
    container_name: 
      task_manager_container
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5041:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TaskManagerDbContext=Server=sql_task_db;Database=taskmanager;User=root;Password=12345;
    depends_on:
      - sql_task_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - docker_sql_network
  
  sql_task_db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=taskmanager
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      docker_sql_network:
        aliases:
        - sql
    

volumes:
  docker_sql_volume:

networks:
  docker_sql_network:

